### ISSUE TITLE
Не могу запустить приложение

### ISSUE THREAD

**Issue by i-am-tama-tama** [r3pr3ss10n/SpoofDPI-Platform#10]
Даже через `правую кнопку мыши -> открыть` выдает такую ошибку

<img width="326" alt="image" src="https://github.com/user-attachments/assets/09e795b6-0ae7-45b1-8a54-0d82c10d714d">

**Comment by i-am-tama-tama** [comment]
Версия: [1.1.1](https://github.com/r3pr3ss10n/SpoofDPI-Platform/releases/tag/1.1.1)

**Comment by r3pr3ss10n** [comment]
из списка приложений мака откройте терминал

напишите туда xattr -d -r com.apple.quarantine

добавьте пробел после команды, после чего прям в терминал переместите приложение. нажмите энтер, после чего попробуйте запустить еще раз
