### ISSUE TITLE
Android version doesn't work.

### ISSUE THREAD

**Issue by Shararamosh** [r3pr3ss10n/SpoofDPI-Platform#2]
I've tried different window size yet it seems Android version doesn't do anything. I tried both VPN and proxy modes. Blocked sites don't open, YouTube keeps stuttering.

**Comment by r3pr3ss10n** [comment]
Probably internet regulator changed something. As it's clarified in README.md this app is just a wrapper for SpoofDPI library. Check issues on that repo as well: you may be not alone and probably there's solution. Once binary with fix will be released I will update app. Or I will check it myself when I will have free time.

**Comment by r3pr3ss10n** [comment]
i've updated bins yesterday, you can check now.

**Comment by kvalera** [comment]
Удалил предыдущюю версию 1.1.0 и установил сегодняшнюю версии 1.1.1, но после установки версия приложения осталась старой 1.1.0
