### ISSUE TITLE
Android app crashes in VPN-mode, doesn't bypass in proxy-mode

### ISSUE THREAD

**Issue by haalogen** [r3pr3ss10n/SpoofDPI-Platform#3]
Version 1.1.1, 1.1.0, 1.0.0
Android 9

Android app crashes when I give access to set up VPN or when I start service in VPN-mode.
In proxy-mode it doesn't crash but doesn't help bypassing.

**Comment by r3pr3ss10n** [comment]
VPN mode uses method that implemented in Android 10+. You can use proxy mode and set proxy on your WIFI settings.

**Comment by russel5** [comment]
Latest version not working at all on android 14, not vpn mode, not proxy.
Version 1.1.0 works, but not helped to spoof YouTube slow speed

**Comment by r3pr3ss10n** [comment]
ill add --debug mode in next ver, so you will be able to see the logs. can't say more right now.

**Comment by r3pr3ss10n** [comment]
the ts issue is resolved, if you have another one please open new topic.
