### ISSUE TITLE
Wrong version number in app details

### ISSUE THREAD

**Issue by aXe1** [r3pr3ss10n/SpoofDPI-Platform#6]
Hi, thank you for the product!

After installing v.1.1.1 from Github Releases, app details shows v.1.1.0. And because v.1.1.0 isn't latest - soft like Obtainium download v.1.1.1, and continiously tries to reinstall it without any abillity to break the loop.

**Comment by r3pr3ss10n** [comment]
Hello. Known, will be fixed in the next version. Thanks!
